import { createFileRoute, Link, redirect } from "@tanstack/react-router";
import { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, FileSpreadsheet, Home, Shield, Upload, Users } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { SectionCard, StatCard } from "@/components/ui-bits";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { supabase } from "@/integrations/supabase/client";
import { flatsQuery, residentsQuery, staffQuery } from "@/lib/api";
import * as XLSX from "xlsx";

export const Route=createFileRoute("/_authenticated/admin")({component:AdminPage , beforeLoad: async () => { const { data:{user} } = await supabase.auth.getUser(); if (!user) throw redirect({ to: "/auth" }); const { data } = await supabase.from("user_roles").select("role").eq("user_id", user.id).eq("role","admin").maybeSingle(); if (!data) throw redirect({ to: "/dashboard" }); } });
function normalize(row:Record<string,unknown>){const o:Record<string,unknown>={};for(const [k,v] of Object.entries(row))o[k.trim().toLowerCase().replace(/[\s-]+/g,"_")]=typeof v==="string"?v.trim():v;return o}
function AdminPage(){
 const qc=useQueryClient();const flats=useQuery(flatsQuery),residents=useQuery(residentsQuery),staff=useQuery(staffQuery);
 const [flatOpen,setFlatOpen]=useState(false),[busy,setBusy]=useState(false);const residentRef=useRef<HTMLInputElement>(null),staffRef=useRef<HTMLInputElement>(null);
 const createFlat=useMutation({mutationFn:async(p:Record<string,unknown>)=>{const {error}=await supabase.from("flats").insert(p as never);if(error)throw new Error(error.message)},onSuccess:()=>{toast.success("Flat created");setFlatOpen(false);qc.invalidateQueries({queryKey:["flats"]})},onError:(e:Error)=>toast.error(e.message)});
 async function importFile(file:File,type:"residents"|"staff"){setBusy(true);try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array"});const rows=(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""}) as Record<string,unknown>[]).map(normalize);if(!rows.length)throw new Error("The file contains no data.");if(rows.length>5000)throw new Error("Maximum 5,000 rows per import batch.");
 if(type==="staff"){const payload=rows.map(r=>({employee_code:String(r.employee_code||r.employee_id||"EMP-"+Date.now()),full_name:String(r.full_name||r.name||""),designation:String(r.designation||r.role||"Staff"),department:String(r.department||"Admin"),phone:String(r.phone||"").replace(/\D/g,""),whatsapp:String(r.whatsapp||r.phone||"").replace(/\D/g,""),shift:String(r.shift||"Morning"),join_date:r.join_date||null,monthly_salary:Number(r.monthly_salary||r.salary||0),status:String(r.status||"active"),address:String(r.address||""),aadhaar_number:String(r.aadhaar_number||r.aadhaar||"").replace(/\D/g,"")}));if(payload.some(r=>!r.full_name||!/^\d{12}$/.test(r.aadhaar_number)||!/^\d{10}$/.test(r.phone)))throw new Error("Every staff row needs a name, 10-digit phone and 12-digit Aadhaar.");const {error}=await supabase.from("staff").insert(payload as never);if(error)throw new Error(error.message)}
 else{const byNo=new Map((flats.data??[]).map(f=>[f.flat_no,f.id]));const payload=rows.map(r=>({flat_id:byNo.get(String(r.flat_no||"").trim())||null,full_name:String(r.full_name||r.name||""),resident_type:String(r.resident_type||r.type||"owner").toLowerCase(),phone:String(r.phone||"").replace(/\D/g,""),whatsapp:String(r.whatsapp||"").replace(/\D/g,""),email:String(r.email||""),move_in_date:r.move_in_date||null,move_out_date:r.move_out_date||null,status:String(r.status||"active"),notes:String(r.notes||"")}));if(payload.some(r=>!r.full_name||!/^\d{10}$/.test(r.phone)))throw new Error("Every resident row needs a name and 10-digit phone.");const {error}=await supabase.from("residents").insert(payload as never);if(error)throw new Error(error.message)}
 toast.success(rows.length+" "+type+" records imported");qc.invalidateQueries({queryKey:[type]});}catch(e){toast.error((e as Error).message)}finally{setBusy(false);if(residentRef.current)residentRef.current.value="";if(staffRef.current)staffRef.current.value=""}}
 return <AppShell title="Admin" description="Administration, data management and access control"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Flats" value={flats.data?.length??0} icon={Building2}/><StatCard label="Residents" value={residents.data?.length??0} icon={Users}/><StatCard label="Staff" value={staff.data?.length??0} icon={Users}/><StatCard label="Access control" value="Active" icon={Shield} tone="success"/></div>
 <div className="mt-6 grid gap-4 md:grid-cols-2"><SectionCard title="Flat management" description="Create a new flat with zone, block and floor."><div className="flex flex-wrap gap-2"><Button onClick={()=>setFlatOpen(true)}><Home className="mr-2 size-4"/>Create New Flat</Button><Button variant="outline" asChild><Link to="/residents">Open Flat Directory</Link></Button></div></SectionCard>
 <SectionCard title="User access" description="Assign access to specific application tabs."><Button asChild><Link to="/admin/user-rights"><Shield className="mr-2 size-4"/>User Rights</Link></Button></SectionCard>
 <SectionCard title="Resident data" description="Upload Excel (.xlsx/.xls) or CSV; up to 5,000 rows per batch."><input ref={residentRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f,"residents")}}/><Button variant="outline" disabled={busy} onClick={()=>residentRef.current?.click()}><FileSpreadsheet className="mr-2 size-4"/>Upload Resident Data</Button></SectionCard>
 <SectionCard title="Staff data" description="Upload Excel (.xlsx/.xls) or CSV; up to 5,000 rows per batch."><input ref={staffRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f,"staff")}}/><Button variant="outline" disabled={busy} onClick={()=>staffRef.current?.click()}><Upload className="mr-2 size-4"/>Upload Staff Data</Button></SectionCard></div>
 <Dialog open={flatOpen} onOpenChange={setFlatOpen}><DialogContent><DialogHeader><DialogTitle>Create New Flat</DialogTitle></DialogHeader><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const s=(k:string)=>String(f.get(k)||"").trim();createFlat.mutate({flat_no:s("flat_no"),zone:s("zone"),block:s("block"),floor:Number(f.get("floor")||0),bedrooms:Number(f.get("bedrooms")||2),area_sqft:Number(f.get("area_sqft")||0)||null,status:"vacant"})}}><div className="space-y-2"><Label>Flat number</Label><Input name="flat_no" required placeholder="A-101"/></div><div className="space-y-2"><Label>Zone</Label><Input name="zone" required/></div><div className="space-y-2"><Label>Block</Label><Input name="block" required/></div><div className="space-y-2"><Label>Floor</Label><Input name="floor" required type="number" min="0"/></div><div className="space-y-2"><Label>Bedrooms</Label><Input name="bedrooms" type="number" min="1" defaultValue="2"/></div><div className="space-y-2"><Label>Area (sq ft)</Label><Input name="area_sqft" type="number" min="0"/></div><div className="sm:col-span-2 flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setFlatOpen(false)}>Cancel</Button><Button type="submit" disabled={createFlat.isPending}>Create Flat</Button></div></form></DialogContent></Dialog></AppShell>
}