import { createFileRoute, redirect } from "@tanstack/react-router";
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AppShell } from "@/components/AppShell";
import { SectionCard } from "@/components/ui-bits";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { settingsQuery, type Settings } from "@/lib/api";
import { toast } from "sonner";
export const Route=createFileRoute("/_authenticated/admin-settings")({component:AdminSettingsPage , beforeLoad: async () => { const { data:{user} } = await supabase.auth.getUser(); if (!user) throw redirect({ to: "/auth" }); const { data } = await supabase.from("user_roles").select("role").eq("user_id", user.id).eq("role","admin").maybeSingle(); if (!data) throw redirect({ to: "/dashboard" }); } });
function AdminSettingsPage(){const qc=useQueryClient(),q=useQuery(settingsQuery);const [form,setForm]=useState<Settings|null>(null),[saving,setSaving]=useState(false);if(q.isLoading)return <AppShell title="Admin · Settings">Loading…</AppShell>;const value=form??q.data;if(!value)return <AppShell title="Admin · Settings"><SectionCard title="Settings"><p>No apartment settings record found.</p></SectionCard></AppShell>;async function save(){setSaving(true);const {id,...payload}=value;const {error}=await supabase.from("apartment_settings").update(payload as never).eq("id",id);if(error)toast.error(error.message);else{toast.success("Settings saved");qc.invalidateQueries({queryKey:["settings"]})}setSaving(false)}const setArr=(k:"blocks"|"zones"|"gates"|"shifts",v:string)=>setForm({...value,[k]:v.split(",").map(x=>x.trim()).filter(Boolean)});return <AppShell title="Admin · Settings" description="Apartment configuration"><div className="grid gap-4 md:grid-cols-2"><SectionCard title="Property"><div className="grid gap-4"><Field label="Name" value={value.name} onChange={v=>setForm({...value,name:v})}/><Field label="Address" value={value.address??""} onChange={v=>setForm({...value,address:v})}/><Field label="City" value={value.city??""} onChange={v=>setForm({...value,city:v})}/><Field label="Total flats" value={String(value.total_flats)} onChange={v=>setForm({...value,total_flats:Number(v)||0})}/></div></SectionCard><SectionCard title="Structure"><div className="grid gap-4"><Field label="Blocks (comma separated)" value={value.blocks.join(", ")} onChange={v=>setArr("blocks",v)}/><Field label="Zones (comma separated)" value={value.zones.join(", ")} onChange={v=>setArr("zones",v)}/><Field label="Gates (comma separated)" value={value.gates.join(", ")} onChange={v=>setArr("gates",v)}/><Field label="Shifts (comma separated)" value={value.shifts.join(", ")} onChange={v=>setArr("shifts",v)}/></div></SectionCard></div><div className="mt-4 flex justify-end"><Button onClick={()=>void save()} disabled={saving}>{saving?"Saving…":"Save Settings"}</Button></div></AppShell>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div className="space-y-2"><Label>{label}</Label><Input value={value} onChange={e=>onChange(e.target.value)}/></div>}
