import { createFileRoute, redirect } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Shield, UserPlus } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { SectionCard } from "@/components/ui-bits";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/admin/user-rights")({component:UserRightsPage , beforeLoad: async () => { const { data:{user} } = await supabase.auth.getUser(); if (!user) throw redirect({ to: "/auth" }); const { data } = await supabase.from("user_roles").select("role").eq("user_id", user.id).eq("role","admin").maybeSingle(); if (!data) throw redirect({ to: "/dashboard" }); } });
const TABS=[["dashboard","Dashboard"],["staff","Staff"],["attendance","Attendance"],["security","Security"],["helpdesk","Help Desk"],["residents","Residents"],["reports","Reports"],["admin","Admin"]] as const;
type Profile={id:string;full_name:string|null;email:string|null};type Perm={user_id:string;tab_key:string;can_view:boolean;can_create:boolean;can_edit:boolean;can_delete:boolean};
function UserRightsPage(){const [users,setUsers]=useState<Profile[]>([]),[selected,setSelected]=useState(""),[perms,setPerms]=useState<Record<string,Perm>>({}),[me,setMe]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;setMe(user.id);const {data,error}=await supabase.from("profiles").select("id,full_name,email").order("created_at");if(error)toast.error(error.message);setUsers(data??[]);setSelected(user.id)})()},[]);
 useEffect(()=>{if(!selected)return;(async()=>{const {data,error}=await supabase.from("user_tab_permissions").select("*").eq("user_id",selected);if(error)toast.error(error.message);const next:Record<string,Perm>={};for(const [k] of TABS)next[k]={user_id:selected,tab_key:k,can_view:k==="dashboard",can_create:false,can_edit:false,can_delete:false};for(const p of data??[])next[p.tab_key]=p;setPerms(next)})()},[selected]);
 async function save(){const {error}=await supabase.from("user_tab_permissions").upsert(Object.values(perms) as never,{onConflict:"user_id,tab_key"});if(error)toast.error(error.message);else toast.success("User rights saved")}
 async function makeAdmin(){const {error}=await supabase.from("user_roles").upsert({user_id:selected,role:"admin"} as never,{onConflict:"user_id,role"});if(error)toast.error(error.message);else toast.success("Administrator access assigned")}
 return <AppShell title="Admin · User Rights" description="Assign access by application tab"><SectionCard title="Users"><div className="mb-5 flex flex-wrap gap-2">{users.map(u=><Button key={u.id} variant={selected===u.id?"default":"outline"} onClick={()=>setSelected(u.id)}>{u.full_name||u.email||u.id.slice(0,8)}{u.id===me?" (You)":""}</Button>)}</div>{selected?<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Tab</th><th className="p-3">View</th><th className="p-3">Create</th><th className="p-3">Edit</th><th className="p-3">Delete</th></tr></thead><tbody>{TABS.map(([key,label])=>{const p=perms[key];return <tr key={key} className="border-b"><td className="p-3 font-medium">{label}</td>{(["can_view","can_create","can_edit","can_delete"] as const).map(k=><td key={k} className="p-3"><input type="checkbox" checked={!!p?.[k]} onChange={e=>setPerms(x=>({...x,[key]:{...x[key],[k]:e.target.checked}}))}/></td>)}</tr>})}</tbody></table></div>:null}<div className="mt-5 flex flex-wrap gap-2"><Button onClick={()=>void save()}><Shield className="mr-2 size-4"/>Save User Rights</Button><Button variant="outline" onClick={()=>void makeAdmin()}><UserPlus className="mr-2 size-4"/>Make Selected User Admin</Button></div></SectionCard></AppShell>}
