import { createFileRoute, redirect } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Plus, Pencil, Power } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/_authenticated/checklist-master")({ component: ChecklistMasterPage, beforeLoad: async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user)throw redirect({to:"/auth"}); const {data}=await supabase.from("user_roles").select("role").eq("user_id",user.id).eq("role","admin").maybeSingle(); if(!data)throw redirect({to:"/dashboard"});} });
const cats=["FM","MC","Security","STP","Plumbing","Garden"]; const freqs=["Daily","Weekly","Monthly","Quarterly","Half-Yearly","Yearly"];
function ChecklistMasterPage(){const [rows,setRows]=useState<any[]>([]);const [task,setTask]=useState("");const [category,setCategory]=useState("FM");const [frequency,setFrequency]=useState("Daily");const [editing,setEditing]=useState<string|null>(null);
async function load(){const {data,error}=await supabase.from("checklist_master").select("*").order("category").order("task");if(error)toast.error(error.message);setRows(data||[]);} useEffect(()=>{void load()},[]);
async function save(){if(!task.trim())return toast.error("Enter a checklist item.");const payload={task:task.trim(),category,frequency};const q=editing?supabase.from("checklist_master").update(payload).eq("id",editing):supabase.from("checklist_master").insert(payload);const {error}=await q;if(error)toast.error(error.message);else{toast.success("Checklist item saved.");setTask("");setEditing(null);void load();}}
async function toggle(r:any){const {error}=await supabase.from("checklist_master").update({active:!r.active}).eq("id",r.id);if(error)toast.error(error.message);else void load();}
return <AppShell title="Check list Master" description="Create, edit and disable checklist items used across all checklists"><div className="rounded-2xl border bg-card p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_180px_180px_auto]"><Input placeholder="Checklist item / task" value={task} onChange={e=>setTask(e.target.value)}/><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{cats.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={frequency} onValueChange={setFrequency}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{freqs.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Button onClick={save} className="gap-2"><Plus className="size-4"/>{editing?"Update":"Add"}</Button></div>{editing&&<Button variant="ghost" size="sm" className="mt-2" onClick={()=>{setEditing(null);setTask("")}}>Cancel edit</Button>}<div className="mt-6 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Category</th><th className="p-3">Checklist Item</th><th className="p-3">Frequency</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b"><td className="p-3">{r.category}</td><td className="p-3 font-medium">{r.task}</td><td className="p-3">{r.frequency}</td><td className="p-3">{r.active?"Active":"Disabled"}</td><td className="p-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>{setEditing(r.id);setTask(r.task);setCategory(r.category);setFrequency(r.frequency)}}><Pencil className="mr-1 size-4"/>Edit</Button><Button size="sm" variant="outline" onClick={()=>void toggle(r)}><Power className="mr-1 size-4"/>{r.active?"Disable":"Enable"}</Button></td></tr>)}</tbody></table></div></div></AppShell>}
