/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHelpdeskRouteImport } from './routes/_authenticated/helpdesk'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedResidentsRouteImport } from './routes/_authenticated/residents'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedFacilityManagementRouteImport } from './routes/_authenticated/facility-management'
import { Route as AuthenticatedContractorRouteImport } from './routes/_authenticated/contractor'
import { Route as AuthenticatedOfficialRecordsRouteImport } from './routes/_authenticated/official-records'
import { Route as AuthenticatedMcRepositoryRouteImport } from './routes/_authenticated/mc-repository'
import { Route as AuthenticatedEcRepositoryRouteImport } from './routes/_authenticated/ec-repository'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin-settings'
import { Route as AuthenticatedAdminUserRightsRouteImport } from './routes/_authenticated/admin-user-rights'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpdeskRoute = AuthenticatedHelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResidentsRoute = AuthenticatedResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff', path: '/staff', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance', path: '/attendance', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacilityManagementRoute = AuthenticatedFacilityManagementRouteImport.update({
  id: '/facility-management', path: '/facility-management', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractorRoute = AuthenticatedContractorRouteImport.update({
  id: '/contractor', path: '/contractor', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficialRecordsRoute = AuthenticatedOfficialRecordsRouteImport.update({
  id: '/official-records', path: '/official-records', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMcRepositoryRoute = AuthenticatedMcRepositoryRouteImport.update({
  id: '/mc-repository', path: '/mc-repository', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcRepositoryRoute = AuthenticatedEcRepositoryRouteImport.update({
  id: '/ec-repository', path: '/ec-repository', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin', path: '/admin', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute = AuthenticatedAdminSettingsRouteImport.update({
  id: '/admin/settings', path: '/admin/settings', getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUserRightsRoute = AuthenticatedAdminUserRightsRouteImport.update({
  id: '/admin/user-rights', path: '/admin/user-rights', getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/helpdesk': typeof AuthenticatedHelpdeskRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/residents': typeof AuthenticatedResidentsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/facility-management': typeof AuthenticatedFacilityManagementRoute
  '/contractor': typeof AuthenticatedContractorRoute
  '/official-records': typeof AuthenticatedOfficialRecordsRoute
  '/mc-repository': typeof AuthenticatedMcRepositoryRoute
  '/ec-repository': typeof AuthenticatedEcRepositoryRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/user-rights': typeof AuthenticatedAdminUserRightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/helpdesk': typeof AuthenticatedHelpdeskRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/residents': typeof AuthenticatedResidentsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/contractor': typeof AuthenticatedContractorRoute
  '/official-records': typeof AuthenticatedOfficialRecordsRoute
  '/mc-repository': typeof AuthenticatedMcRepositoryRoute
  '/ec-repository': typeof AuthenticatedEcRepositoryRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/user-rights': typeof AuthenticatedAdminUserRightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/helpdesk': typeof AuthenticatedHelpdeskRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/residents': typeof AuthenticatedResidentsRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/facility-management': typeof AuthenticatedFacilityManagementRoute
  '/_authenticated/contractor': typeof AuthenticatedContractorRoute
  '/_authenticated/official-records': typeof AuthenticatedOfficialRecordsRoute
  '/_authenticated/mc-repository': typeof AuthenticatedMcRepositoryRoute
  '/_authenticated/ec-repository': typeof AuthenticatedEcRepositoryRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/user-rights': typeof AuthenticatedAdminUserRightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/helpdesk'
    | '/reports'
    | '/residents'
    | '/security'
    | '/settings'
    | '/staff'
    | '/attendance'
    | '/facility-management'
    | '/contractor'
    | '/official-records'
    | '/mc-repository'
    | '/ec-repository'
    | '/admin'
    | '/admin/settings'
    | '/admin/user-rights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/helpdesk'
    | '/reports'
    | '/residents'
    | '/security'
    | '/settings'
    | '/staff'
    | '/attendance'
    | '/contractor'
    | '/official-records'
    | '/mc-repository'
    | '/ec-repository'
    | '/admin'
    | '/admin/settings'
    | '/admin/user-rights'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/helpdesk'
    | '/_authenticated/reports'
    | '/_authenticated/residents'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/attendance'
    | '/_authenticated/facility-management'
    | '/_authenticated/contractor'
    | '/_authenticated/official-records'
    | '/_authenticated/mc-repository'
    | '/_authenticated/ec-repository'
    | '/_authenticated/admin'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/user-rights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/helpdesk': {
      id: '/_authenticated/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof AuthenticatedHelpdeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/residents': {
      id: '/_authenticated/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof AuthenticatedResidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': { id: '/_authenticated/staff'; path: '/staff'; fullPath: '/staff'; preLoaderRoute: typeof AuthenticatedStaffRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/attendance': { id: '/_authenticated/attendance'; path: '/attendance'; fullPath: '/attendance'; preLoaderRoute: typeof AuthenticatedAttendanceRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/facility-management': { id: '/_authenticated/facility-management'; path: '/facility-management'; fullPath: '/facility-management'; preLoaderRoute: typeof AuthenticatedFacilityManagementRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/contractor': { id: '/_authenticated/contractor'; path: '/contractor'; fullPath: '/contractor'; preLoaderRoute: typeof AuthenticatedContractorRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/official-records': { id: '/_authenticated/official-records'; path: '/official-records'; fullPath: '/official-records'; preLoaderRoute: typeof AuthenticatedOfficialRecordsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/mc-repository': { id: '/_authenticated/mc-repository'; path: '/mc-repository'; fullPath: '/mc-repository'; preLoaderRoute: typeof AuthenticatedMcRepositoryRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/ec-repository': { id: '/_authenticated/ec-repository'; path: '/ec-repository'; fullPath: '/ec-repository'; preLoaderRoute: typeof AuthenticatedEcRepositoryRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/admin': { id: '/_authenticated/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AuthenticatedAdminRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/admin/settings': { id: '/_authenticated/admin/settings'; path: '/admin/settings'; fullPath: '/admin/settings'; preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/admin/user-rights': { id: '/_authenticated/admin/user-rights'; path: '/admin/user-rights'; fullPath: '/admin/user-rights'; preLoaderRoute: typeof AuthenticatedAdminUserRightsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpdeskRoute: typeof AuthenticatedHelpdeskRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedResidentsRoute: typeof AuthenticatedResidentsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedFacilityManagementRoute: typeof AuthenticatedFacilityManagementRoute
  AuthenticatedContractorRoute: typeof AuthenticatedContractorRoute
  AuthenticatedOfficialRecordsRoute: typeof AuthenticatedOfficialRecordsRoute
  AuthenticatedMcRepositoryRoute: typeof AuthenticatedMcRepositoryRoute
  AuthenticatedEcRepositoryRoute: typeof AuthenticatedEcRepositoryRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUserRightsRoute: typeof AuthenticatedAdminUserRightsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpdeskRoute: AuthenticatedHelpdeskRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedResidentsRoute: AuthenticatedResidentsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedFacilityManagementRoute: AuthenticatedFacilityManagementRoute,
  AuthenticatedContractorRoute: AuthenticatedContractorRoute,
  AuthenticatedOfficialRecordsRoute: AuthenticatedOfficialRecordsRoute,
  AuthenticatedMcRepositoryRoute: AuthenticatedMcRepositoryRoute,
  AuthenticatedEcRepositoryRoute: AuthenticatedEcRepositoryRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUserRightsRoute: AuthenticatedAdminUserRightsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
