/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin-settings'
import { Route as AuthenticatedAdminUserRightsRouteImport } from './routes/_authenticated/admin-user-rights'
import { Route as AuthenticatedAssetManagementRouteImport } from './routes/_authenticated/asset-management'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedByeLawRepositoryRouteImport } from './routes/_authenticated/bye-law-repository'
import { Route as AuthenticatedCheckListRouteImport } from './routes/_authenticated/check-list'
import { Route as AuthenticatedChecklistMasterRouteImport } from './routes/_authenticated/checklist-master'
import { Route as AuthenticatedContractorRouteImport } from './routes/_authenticated/contractor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEcRepositoryRouteImport } from './routes/_authenticated/ec-repository'
import { Route as AuthenticatedFacilityManagementRouteImport } from './routes/_authenticated/facility-management'
import { Route as AuthenticatedHelpdeskRouteImport } from './routes/_authenticated/helpdesk'
import { Route as AuthenticatedHolidayListRouteImport } from './routes/_authenticated/holiday-list'
import { Route as AuthenticatedIntegrationMasterRouteImport } from './routes/_authenticated/integration-master'\nimport { Route as AuthenticatedLetterHeadRouteImport } from './routes/_authenticated/letter-head'
import { Route as AuthenticatedMcHandbookRouteImport } from './routes/_authenticated/mc-handbook'
import { Route as AuthenticatedMcRepositoryRouteImport } from './routes/_authenticated/mc-repository'
import { Route as AuthenticatedOfficialRecordsRouteImport } from './routes/_authenticated/official-records'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedResidentsRouteImport } from './routes/_authenticated/residents'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedUserManagementRouteImport } from './routes/_authenticated/user-management'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin-settings',
    path: '/admin-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUserRightsRoute =
  AuthenticatedAdminUserRightsRouteImport.update({
    id: '/admin-user-rights',
    path: '/admin-user-rights',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetManagementRoute =
  AuthenticatedAssetManagementRouteImport.update({
    id: '/asset-management',
    path: '/asset-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedByeLawRepositoryRoute =
  AuthenticatedByeLawRepositoryRouteImport.update({
    id: '/bye-law-repository',
    path: '/bye-law-repository',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckListRoute = AuthenticatedCheckListRouteImport.update({
  id: '/check-list',
  path: '/check-list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistMasterRoute =
  AuthenticatedChecklistMasterRouteImport.update({
    id: '/checklist-master',
    path: '/checklist-master',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractorRoute = AuthenticatedContractorRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcRepositoryRoute =
  AuthenticatedEcRepositoryRouteImport.update({
    id: '/ec-repository',
    path: '/ec-repository',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacilityManagementRoute =
  AuthenticatedFacilityManagementRouteImport.update({
    id: '/facility-management',
    path: '/facility-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpdeskRoute = AuthenticatedHelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHolidayListRoute =
  AuthenticatedHolidayListRouteImport.update({
    id: '/holiday-list',
    path: '/holiday-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationMasterRoute =
  AuthenticatedIntegrationMasterRouteImport.update({
    id: '/integration-master',
    path: '/integration-master',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLetterHeadRoute = AuthenticatedLetterHeadRouteImport.update({\n  id: '/letter-head',\n  path: '/letter-head',\n  getParentRoute: () => AuthenticatedRouteRoute,\n} as any)\nconst AuthenticatedMcHandbookRoute = AuthenticatedMcHandbookRouteImport.update({
  id: '/mc-handbook',
  path: '/mc-handbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMcRepositoryRoute =
  AuthenticatedMcRepositoryRouteImport.update({
    id: '/mc-repository',
    path: '/mc-repository',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficialRecordsRoute =
  AuthenticatedOfficialRecordsRouteImport.update({
    id: '/official-records',
    path: '/official-records',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResidentsRoute = AuthenticatedResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserManagementRoute =
  AuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/admin-user-rights': typeof AuthenticatedAdminUserRightsRoute
  '/asset-management': typeof AuthenticatedAssetManagementRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/bye-law-repository': typeof AuthenticatedByeLawRepositoryRoute
  '/check-list': typeof AuthenticatedCheckListRoute
  '/checklist-master': typeof AuthenticatedChecklistMasterRoute
  '/contractor': typeof AuthenticatedContractorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ec-repository': typeof AuthenticatedEcRepositoryRoute
  '/facility-management': typeof AuthenticatedFacilityManagementRoute
  '/helpdesk': typeof AuthenticatedHelpdeskRoute
  '/holiday-list': typeof AuthenticatedHolidayListRoute
  '/integration-master': typeof AuthenticatedIntegrationMasterRoute
  '/mc-handbook': typeof AuthenticatedMcHandbookRoute
  '/mc-repository': typeof AuthenticatedMcRepositoryRoute
  '/official-records': typeof AuthenticatedOfficialRecordsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/residents': typeof AuthenticatedResidentsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/admin-user-rights': typeof AuthenticatedAdminUserRightsRoute
  '/asset-management': typeof AuthenticatedAssetManagementRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/bye-law-repository': typeof AuthenticatedByeLawRepositoryRoute
  '/check-list': typeof AuthenticatedCheckListRoute
  '/checklist-master': typeof AuthenticatedChecklistMasterRoute
  '/contractor': typeof AuthenticatedContractorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ec-repository': typeof AuthenticatedEcRepositoryRoute
  '/facility-management': typeof AuthenticatedFacilityManagementRoute
  '/helpdesk': typeof AuthenticatedHelpdeskRoute
  '/holiday-list': typeof AuthenticatedHolidayListRoute
  '/integration-master': typeof AuthenticatedIntegrationMasterRoute
  '/mc-handbook': typeof AuthenticatedMcHandbookRoute
  '/mc-repository': typeof AuthenticatedMcRepositoryRoute
  '/official-records': typeof AuthenticatedOfficialRecordsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/residents': typeof AuthenticatedResidentsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin-user-rights': typeof AuthenticatedAdminUserRightsRoute
  '/_authenticated/asset-management': typeof AuthenticatedAssetManagementRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/bye-law-repository': typeof AuthenticatedByeLawRepositoryRoute
  '/_authenticated/check-list': typeof AuthenticatedCheckListRoute
  '/_authenticated/checklist-master': typeof AuthenticatedChecklistMasterRoute
  '/_authenticated/contractor': typeof AuthenticatedContractorRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ec-repository': typeof AuthenticatedEcRepositoryRoute
  '/_authenticated/facility-management': typeof AuthenticatedFacilityManagementRoute
  '/_authenticated/helpdesk': typeof AuthenticatedHelpdeskRoute
  '/_authenticated/holiday-list': typeof AuthenticatedHolidayListRoute
  '/_authenticated/integration-master': typeof AuthenticatedIntegrationMasterRoute
  '/_authenticated/mc-handbook': typeof AuthenticatedMcHandbookRoute
  '/_authenticated/mc-repository': typeof AuthenticatedMcRepositoryRoute
  '/_authenticated/official-records': typeof AuthenticatedOfficialRecordsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/residents': typeof AuthenticatedResidentsRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/user-management': typeof AuthenticatedUserManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin-settings'
    | '/admin-user-rights'
    | '/asset-management'
    | '/attendance'
    | '/audit-log'
    | '/bye-law-repository'
    | '/check-list'
    | '/checklist-master'
    | '/contractor'
    | '/dashboard'
    | '/ec-repository'
    | '/facility-management'
    | '/helpdesk'
    | '/holiday-list'
    | '/integration-master'
    | '/mc-handbook'
    | '/mc-repository'
    | '/official-records'
    | '/reports'
    | '/residents'
    | '/security'
    | '/settings'
    | '/staff'
    | '/user-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin-settings'
    | '/admin-user-rights'
    | '/asset-management'
    | '/attendance'
    | '/audit-log'
    | '/bye-law-repository'
    | '/check-list'
    | '/checklist-master'
    | '/contractor'
    | '/dashboard'
    | '/ec-repository'
    | '/facility-management'
    | '/helpdesk'
    | '/holiday-list'
    | '/integration-master'
    | '/mc-handbook'
    | '/mc-repository'
    | '/official-records'
    | '/reports'
    | '/residents'
    | '/security'
    | '/settings'
    | '/staff'
    | '/user-management'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin-settings'
    | '/_authenticated/admin-user-rights'
    | '/_authenticated/asset-management'
    | '/_authenticated/attendance'
    | '/_authenticated/audit-log'
    | '/_authenticated/bye-law-repository'
    | '/_authenticated/check-list'
    | '/_authenticated/checklist-master'
    | '/_authenticated/contractor'
    | '/_authenticated/dashboard'
    | '/_authenticated/ec-repository'
    | '/_authenticated/facility-management'
    | '/_authenticated/helpdesk'
    | '/_authenticated/holiday-list'
    | '/_authenticated/integration-master'
    | '/_authenticated/mc-handbook'
    | '/_authenticated/mc-repository'
    | '/_authenticated/official-records'
    | '/_authenticated/reports'
    | '/_authenticated/residents'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/user-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-settings': {
      id: '/_authenticated/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-user-rights': {
      id: '/_authenticated/admin-user-rights'
      path: '/admin-user-rights'
      fullPath: '/admin-user-rights'
      preLoaderRoute: typeof AuthenticatedAdminUserRightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asset-management': {
      id: '/_authenticated/asset-management'
      path: '/asset-management'
      fullPath: '/asset-management'
      preLoaderRoute: typeof AuthenticatedAssetManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bye-law-repository': {
      id: '/_authenticated/bye-law-repository'
      path: '/bye-law-repository'
      fullPath: '/bye-law-repository'
      preLoaderRoute: typeof AuthenticatedByeLawRepositoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/check-list': {
      id: '/_authenticated/check-list'
      path: '/check-list'
      fullPath: '/check-list'
      preLoaderRoute: typeof AuthenticatedCheckListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist-master': {
      id: '/_authenticated/checklist-master'
      path: '/checklist-master'
      fullPath: '/checklist-master'
      preLoaderRoute: typeof AuthenticatedChecklistMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contractor': {
      id: '/_authenticated/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof AuthenticatedContractorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ec-repository': {
      id: '/_authenticated/ec-repository'
      path: '/ec-repository'
      fullPath: '/ec-repository'
      preLoaderRoute: typeof AuthenticatedEcRepositoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facility-management': {
      id: '/_authenticated/facility-management'
      path: '/facility-management'
      fullPath: '/facility-management'
      preLoaderRoute: typeof AuthenticatedFacilityManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/helpdesk': {
      id: '/_authenticated/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof AuthenticatedHelpdeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/holiday-list': {
      id: '/_authenticated/holiday-list'
      path: '/holiday-list'
      fullPath: '/holiday-list'
      preLoaderRoute: typeof AuthenticatedHolidayListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integration-master': {
      id: '/_authenticated/integration-master'
      path: '/integration-master'
      fullPath: '/integration-master'
      preLoaderRoute: typeof AuthenticatedIntegrationMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mc-handbook': {
      id: '/_authenticated/mc-handbook'
      path: '/mc-handbook'
      fullPath: '/mc-handbook'
      preLoaderRoute: typeof AuthenticatedMcHandbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mc-repository': {
      id: '/_authenticated/mc-repository'
      path: '/mc-repository'
      fullPath: '/mc-repository'
      preLoaderRoute: typeof AuthenticatedMcRepositoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/official-records': {
      id: '/_authenticated/official-records'
      path: '/official-records'
      fullPath: '/official-records'
      preLoaderRoute: typeof AuthenticatedOfficialRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/residents': {
      id: '/_authenticated/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof AuthenticatedResidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-management': {
      id: '/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUserRightsRoute: typeof AuthenticatedAdminUserRightsRoute
  AuthenticatedAssetManagementRoute: typeof AuthenticatedAssetManagementRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedByeLawRepositoryRoute: typeof AuthenticatedByeLawRepositoryRoute
  AuthenticatedCheckListRoute: typeof AuthenticatedCheckListRoute
  AuthenticatedChecklistMasterRoute: typeof AuthenticatedChecklistMasterRoute
  AuthenticatedContractorRoute: typeof AuthenticatedContractorRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEcRepositoryRoute: typeof AuthenticatedEcRepositoryRoute
  AuthenticatedFacilityManagementRoute: typeof AuthenticatedFacilityManagementRoute
  AuthenticatedHelpdeskRoute: typeof AuthenticatedHelpdeskRoute
  AuthenticatedHolidayListRoute: typeof AuthenticatedHolidayListRoute
  AuthenticatedIntegrationMasterRoute: typeof AuthenticatedIntegrationMasterRoute
  AuthenticatedMcHandbookRoute: typeof AuthenticatedMcHandbookRoute
  AuthenticatedMcRepositoryRoute: typeof AuthenticatedMcRepositoryRoute
  AuthenticatedOfficialRecordsRoute: typeof AuthenticatedOfficialRecordsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedResidentsRoute: typeof AuthenticatedResidentsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedUserManagementRoute: typeof AuthenticatedUserManagementRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUserRightsRoute: AuthenticatedAdminUserRightsRoute,
  AuthenticatedAssetManagementRoute: AuthenticatedAssetManagementRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedByeLawRepositoryRoute: AuthenticatedByeLawRepositoryRoute,
  AuthenticatedCheckListRoute: AuthenticatedCheckListRoute,
  AuthenticatedChecklistMasterRoute: AuthenticatedChecklistMasterRoute,
  AuthenticatedContractorRoute: AuthenticatedContractorRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEcRepositoryRoute: AuthenticatedEcRepositoryRoute,
  AuthenticatedFacilityManagementRoute: AuthenticatedFacilityManagementRoute,
  AuthenticatedHelpdeskRoute: AuthenticatedHelpdeskRoute,
  AuthenticatedHolidayListRoute: AuthenticatedHolidayListRoute,
  AuthenticatedIntegrationMasterRoute: AuthenticatedIntegrationMasterRoute,
  AuthenticatedMcHandbookRoute: AuthenticatedMcHandbookRoute,
  AuthenticatedMcRepositoryRoute: AuthenticatedMcRepositoryRoute,
  AuthenticatedOfficialRecordsRoute: AuthenticatedOfficialRecordsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedResidentsRoute: AuthenticatedResidentsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedUserManagementRoute: AuthenticatedUserManagementRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
